/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<gpio.h>
void delay(){
	for(int i =0; i<500000;i++);
}
int main(void)
{
    /* Loop forever */
	uint8_t pin =  5;
	GPIOA_Init();
	GPIOA_SetOut(pin);

	while(1){
		GPIOA_High(pin);
		delay();
		GPIO_Low(pin);
		delay();
	}
}
